/*
    bit.h -- Build It Configuration Header for linux-i686

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

#define BLD_PRODUCT "http"
#define BLD_NAME "Http Library"
#define BLD_COMPANY "Embedthis"
#define BLD_HTTP_PRODUCT 1
#define BLD_VERSION "1.0.0"
#define BLD_NUMBER "B2"
#define BLD_MAJOR_VERSION 1
#define BLD_MINOR_VERSION 0
#define BLD_PATCH_VERSION 0
#define BLD_VNUM 100000000
#define BLD_CONFIG_CMD "bit -emulate linux-i686 -without all configure -gen sh,make"
#define BLD_LIB_NAME "bin"
#define BLD_CFG_PREFIX "/etc/http"
#define BLD_BIN_PREFIX "/usr/lib/http/1.0.0/bin"
#define BLD_DOC_PREFIX "/usr/lib/http/doc"
#define BLD_INC_PREFIX "/usr/lib/http/1.0.0/inc"
#define BLD_JEM_PREFIX "/usr/lib/http/jems"
#define BLD_LIB_PREFIX "/usr/lib/http/1.0.0/bin"
#define BLD_LOG_PREFIX "/var/log/http"
#define BLD_MAN_PREFIX "/usr/lib/http/man"
#define BLD_PRD_PREFIX "/usr/lib/http"
#define BLD_SAM_PREFIX "/usr/lib/http/samples"
#define BLD_SPL_PREFIX "/var/spool/http"
#define BLD_SRC_PREFIX "/usr/src/http-1.0.0"
#define BLD_VER_PREFIX "/usr/lib/http/1.0.0"
#define BLD_WEB_PREFIX "/var/www/http-default"
#define BLD_EXE ""
#define BLD_SHLIB ".so"
#define BLD_SHOBJ ".so"
#define BLD_LIB ".a"
#define BLD_OBJ ".o"
#define BLD_CC_DOUBLE_BRACES 0
#define BLD_CC_DYN_LOAD 1
#define BLD_CC_EDITLINE 0
#define BLD_CC_MMU 1
#define BLD_CC_MTUNE 1
#define BLD_CC_PAM 1
#define BLD_CC_STACK_PROTECTOR 1
#define BLD_CC_SYNC 1
#define BLD_CC_SYNC_CAS 1
#define BLD_CC_UNNAMED_UNIONS 1
#define BLD_CC_WARN_64TO32 0
#define BLD_CC_WARN_UNUSED 1
#define BLD_FEATURE_ALL 0
#define BLD_FEATURE_CC 1
#define BLD_CC "gcc"
#define BLD_FEATURE_LINK 1
#define BLD_LINK "ld"
#define BLD_FEATURE_PCRE 1
#define BLD_PCRE "/Users/mob/git/http/src/deps/pcre"
#define BLD_FEATURE_DOXYGEN 1
#define BLD_DOXYGEN "/usr/local/bin/doxygen"
#define BLD_FEATURE_DSI 1
#define BLD_DSI "/Users/mob/git/appweb.stable/build/bin/dsi"
#define BLD_FEATURE_EJS 1
#define BLD_EJS "/Users/mob/git/ejs/macosx-x86_64-debug/bin/ejs"
#define BLD_FEATURE_MAN 1
#define BLD_MAN "/usr/bin/man"
#define BLD_FEATURE_MAN2HTML 1
#define BLD_MAN2HTML "/usr/local/bin/man2html"
#define BLD_FEATURE_OPENSSL 0
#define BLD_FEATURE_MATRIXSSL 0
#define BLD_FEATURE_SSL 0
#define BLD_FEATURE_UTEST 1
#define BLD_UTEST "/Users/mob/git/appweb.stable/build/bin/utest"
