/*
    bit.h -- Build It Configuration Header for win-x86

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

#define BLD_PRODUCT "http"
#define BLD_NAME "Http Library"
#define BLD_COMPANY "Embedthis"
#define BLD_HTTP_PRODUCT 1
#define BLD_VERSION "1.0.0"
#define BLD_NUMBER "B2"
#define BLD_MAJOR_VERSION 1
#define BLD_MINOR_VERSION 0
#define BLD_PATCH_VERSION 0
#define BLD_VNUM 100000000
#define BLD_CONFIG_CMD "bit -emulate win-x86 -without all configure -gen sh,nmake,vs"
#define BLD_LIB_NAME "bin"
#define BLD_CFG_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library"
#define BLD_BIN_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library/bin"
#define BLD_DOC_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library/doc"
#define BLD_INC_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library/inc"
#define BLD_JEM_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library/jems"
#define BLD_LIB_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library/bin"
#define BLD_LOG_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library/logs"
#define BLD_MAN_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library/man"
#define BLD_PRD_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library"
#define BLD_SAM_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library/samples"
#define BLD_SPL_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library/tmp"
#define BLD_SRC_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library/src"
#define BLD_VER_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library"
#define BLD_WEB_PREFIX "/Users/mob/git/http/C:/Program Files/Http Library/web"
#define BLD_EXE ".exe"
#define BLD_SHLIB ".lib"
#define BLD_SHOBJ ".dll"
#define BLD_LIB ".a"
#define BLD_OBJ ".obj"
#define BLD_MANAGER ""
#define BLD_CC_DOUBLE_BRACES 0
#define BLD_CC_DYN_LOAD 1
#define BLD_CC_EDITLINE 0
#define BLD_CC_MMU 1
#define BLD_CC_MTUNE 0
#define BLD_CC_PAM 0
#define BLD_CC_STACK_PROTECTOR 0
#define BLD_CC_SYNC 0
#define BLD_CC_SYNC_CAS 0
#define BLD_CC_UNNAMED_UNIONS 1
#define BLD_CC_WARN_64TO32 0
#define BLD_CC_WARN_UNUSED 0
#define BLD_FEATURE_ALL 0
#define BLD_FEATURE_WINSDK 1
#define BLD_WINSDK "$(SDK)"
#define BLD_FEATURE_CC 1
#define BLD_CC "cl.exe"
#define BLD_FEATURE_LINK 1
#define BLD_LINK "link.exe"
#define BLD_FEATURE_DUMPBIN 1
#define BLD_DUMPBIN "dumpbin"
#define BLD_FEATURE_RC 1
#define BLD_RC "rc"
#define BLD_FEATURE_PCRE 1
#define BLD_PCRE "/Users/mob/git/http/src/deps/pcre"
#define BLD_FEATURE_INNO 0
#define BLD_FEATURE_DOXYGEN 1
#define BLD_DOXYGEN "/usr/local/bin/doxygen"
#define BLD_FEATURE_DSI 1
#define BLD_DSI "/usr/local/bin/dsi"
#define BLD_FEATURE_EJS 1
#define BLD_EJS "/Users/mob/git/ejs/macosx-x86_64-debug/bin/ejs"
#define BLD_FEATURE_MAN 1
#define BLD_MAN "/usr/bin/man"
#define BLD_FEATURE_MAN2HTML 1
#define BLD_MAN2HTML "/usr/local/bin/man2html"
#define BLD_FEATURE_OPENSSL 0
#define BLD_FEATURE_MATRIXSSL 0
#define BLD_FEATURE_SSL 0
#define BLD_FEATURE_UTEST 1
#define BLD_UTEST "/Users/mob/git/ejs/macosx-x86_64-debug/bin/utest"
