/*
    bit.h -- Build It Configuration Header for linux-x86

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

#define BIT_PRODUCT "http"
#define BIT_NAME "Http Library"
#define BIT_COMPANY "Embedthis"
#define BIT_HTTP_PRODUCT 1
#define BIT_VERSION "1.0.0"
#define BIT_NUMBER "B2"
#define BIT_MAJOR_VERSION 1
#define BIT_MINOR_VERSION 0
#define BIT_PATCH_VERSION 0
#define BIT_VNUM 100000000
#define BIT_CONFIG_CMD "bit -d -q -platform linux-x86 -without all -configure . -gen sh,make"
#define BIT_PROFILE "debug"
#define BIT_CFG_PREFIX "/etc/http"
#define BIT_BIN_PREFIX "/usr/lib/http/1.0.0/bin"
#define BIT_INC_PREFIX "/usr/lib/http/1.0.0/inc"
#define BIT_LOG_PREFIX "/var/log/http"
#define BIT_PRD_PREFIX "/usr/lib/http"
#define BIT_SPL_PREFIX "/var/spool/http"
#define BIT_SRC_PREFIX "/usr/src/http-1.0.0"
#define BIT_VER_PREFIX "/usr/lib/http/1.0.0"
#define BIT_WEB_PREFIX "/var/www/http-default"
#define BIT_EXE ""
#define BIT_SHLIB ".so"
#define BIT_SHOBJ ".so"
#define BIT_LIB ".a"
#define BIT_OBJ ".o"
#define BIT_MANAGER ""
#define BIT_CC_DOUBLE_BRACES 0
#define BIT_CC_DYN_LOAD 1
#define BIT_CC_EDITLINE 0
#define BIT_CC_MMU 1
#define BIT_CC_MTUNE 1
#define BIT_CC_PAM 0
#define BIT_CC_STACK_PROTECTOR 1
#define BIT_CC_SYNC 1
#define BIT_CC_SYNC_CAS 1
#define BIT_CC_UNNAMED_UNIONS 1
#define BIT_CC_WARN_64TO32 0
#define BIT_CC_WARN_UNUSED 1
#define BIT_FEATURE_DOXYGEN 0
#define BIT_FEATURE_DSI 0
#define BIT_FEATURE_MAN 0
#define BIT_FEATURE_MAN2HTML 0
#define BIT_FEATURE_PMAKER 0
#define BIT_FEATURE_SSL 0
#define BIT_FEATURE_CC 1
#define BIT_FEATURE_LINK 1
#define BIT_FEATURE_PCRE 1
#define BIT_FEATURE_EJS 1
#define BIT_FEATURE_OPENSSL 0
#define BIT_FEATURE_MATRIXSSL 0
#define BIT_FEATURE_UTEST 1
