/*
 *  Initialize for MPR unit tests
 */

require ejs.test 

let PIDFILE = ".appweb.pid"
let HTTP = "http://127.0.0.1:6600"
let path = null

for each (file in find("appweb/web", "*.mod")) {
    rm(file)
}
cleanDir("appweb/web/tmp")

/*
 *   Stop an old web server
 */
if (exists(PIDFILE)) {
    path = Path(PIDFILE)
    pid = path.readString()
    path.remove()
    try {
        kill(pid, 1)
    } catch {}
}

try { 
    path = sh("/usr/bin/which appweb")
    if (path) {
        if (!App.getenv("NOSERVER")) {
            /*
             *   Start a web server for testing. Use webs to wrap appweb to get a clean env.
             */
            pid = System.daemon(path + " --name forMprTest --config appweb/appweb.conf")
            Path(PIDFILE).write(pid)
            share("appwebPidFile", PIDFILE)

            http = new Http
            for (i in 50) {
                try { 
                    http.get(HTTP + "/alive.html")
                } catch {}
                if (http.code == 200) break
                App.sleep(250)
            }
            if (http.code != 200) throw "Can't start web server"
        }
        share("http", HTTP)
    }
} catch (e) { }
